### ISSUE TITLE
can have more time about more function,  many function missing in graph

### ISSUE THREAD

**Issue by hunjixin** [tikv/pprof-rs#28]

**Comment by YangKeao** [comment]
Can you give more detail about this issue? 

- Do you generate the flamegraph or go-pprof protobuf file?

- What does the result flamegraph look like?

**Comment by hunjixin** [comment]
![image](https://user-images.githubusercontent.com/41407352/87134158-dde24f80-c2ca-11ea-85a4-5a39a40c2005.png)

most blank space in left.  so why do not show which or some func exec time here

**Comment by YangKeao** [comment]
@hunjixin The blank part means the time cost in the function but not in sub-function. For your example, the blank part represents the time costs directly in compress256 (without deeper stack).

It shows that most calculations are done directly in the function. The functions called by it (such as `__mm__sha256rnds2_epu32` ) costs less than half of the time.

**Comment by hunjixin** [comment]
@YangKeao is there any way to catch time of  inline function exec time?

**Comment by YangKeao** [comment]
@hunjixin Actually the frame information is provided by `libgcc`'s unwind and `backtrace-rs`, and they do have inline information. In `pprof-rs` we handle inline functions in this way: compact them into one line and split with `/`.

For example, function A inline called function B will be treated as function `A/B` in the graph. We do this compaction because in production `Future` related functions are quite deep and annoying, but they can be inlined into few functions.

But if you find your inline functions are missing, it can be a bug in `libgcc`'s unwind or `backtrace-rs` :cry:

**Comment by YangKeao** [comment]
I will close this issue and if you still have more questions feel free to reopen it :beers:
